name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
#      - 'README.md'

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set-var.outputs.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set var
        id: set-var
        run: |
          echo ::set-output name=ECR_REGISTRY::${{ steps.login-ecr.outputs.registry }}
          echo ::set-output name=ECR_REPOSITORY::ecrtest
          echo ::set-output name=IMAGE_TAG::${{ github.run_number }}
      
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
        
    #  - name: Setup Gradle
    #    uses: maven/maven-build-action@v3

    #  - name: chmod 
    #    run: chmod +x ./gradlew  

      - name: Execute maven build
        run: mvn clean package

      - name: Docker image Build
        id: build-image
        run: |
          docker build \
            -f Dockerfile \
            -t ${{ steps.set-var.outputs.ECR_REGISTRY }}/${{ steps.set-var.outputs.ECR_REPOSITORY }}:${{ steps.set-var.outputs.IMAGE_TAG}} .

      - name: Docker image Push
        id: push-image
        run: |
          docker push ${{ steps.set-var.outputs.ECR_REGISTRY }}/${{ steps.set-var.outputs.ECR_REPOSITORY }}:${{ steps.set-var.outputs.IMAGE_TAG }}
      - name: Checkout Other Repository
        uses: actions/checkout@v2
        with:
          repository: pcmin929/deployment
          ref: main  # branch
          token: ${{ secrets.GH_TOKEN }}
      - name: k8s manifest update
        run: |
          sed -i "s@
          image: ${{ steps.set-var.outputs.ECR_REGISTRY }}/${{ steps.set-var.outputs.ECR_REPOSITORY }}:.*@ \
          image: ${{ steps.set-var.outputs.ECR_REGISTRY }}/${{ steps.set-var.outputs.ECR_REPOSITORY }}:${{ steps.set-var.outputs.IMAGE_TAG }}@g" deployment.yml
      - name: Commit and Push
        run: |
          git config user.email "pcmin929@gmail.com"
          git config user.name "pcmin929"
          git add deployment.yml
          git commit -m "Update image tag"
          git push origin main
